-- Migration: Add trading_signals table for live signal tracking
-- Created: 2026-02-01
-- Purpose: Store live trading signals from signal generator

-- ============================================================================
-- Trading Signals Table
-- ============================================================================

CREATE TABLE IF NOT EXISTS backtester.trading_signals (
    id SERIAL PRIMARY KEY,

    -- Signal identification
    signal_id UUID UNIQUE NOT NULL DEFAULT gen_random_uuid(),
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Market data
    symbol VARCHAR(50) NOT NULL,
    timeframe VARCHAR(10) NOT NULL,
    exchange VARCHAR(50) DEFAULT 'binance',

    -- Trade direction and entry
    side VARCHAR(10) NOT NULL CHECK (side IN ('long', 'short')),
    entry_price NUMERIC(20, 8) NOT NULL,

    -- Exit levels
    take_profit_percent NUMERIC(10, 4),
    take_profit_price NUMERIC(20, 8),
    stop_loss_percent NUMERIC(10, 4),
    stop_loss_price NUMERIC(20, 8),

    -- DCA configuration (if applicable)
    dca_enabled BOOLEAN DEFAULT FALSE,
    dca_grid JSONB,  -- Array of DCA steps

    -- Indicator values at signal time
    indicators JSONB NOT NULL,  -- RSI, EMA, ADX, MACD, etc.

    -- Strategy info
    strategy_name VARCHAR(255),
    strategy_config JSONB,

    -- Signal status
    status VARCHAR(20) NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'notified', 'executed', 'cancelled', 'expired')),

    -- Telegram notification
    telegram_user_id VARCHAR(100),
    notification_sent_at TIMESTAMPTZ,
    notification_status VARCHAR(20) DEFAULT 'pending'
        CHECK (notification_status IN ('pending', 'sent', 'failed')),

    -- Metadata
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),

    -- Additional notes
    notes TEXT,

    -- Signal quality score (0-100)
    quality_score NUMERIC(5, 2) DEFAULT 0.0
);

-- ============================================================================
-- Indexes for performance
-- ============================================================================

CREATE INDEX IF NOT EXISTS idx_trading_signals_signal_id
    ON backtester.trading_signals(signal_id);

CREATE INDEX IF NOT EXISTS idx_trading_signals_timestamp
    ON backtester.trading_signals(timestamp DESC);

CREATE INDEX IF NOT EXISTS idx_trading_signals_symbol
    ON backtester.trading_signals(symbol);

CREATE INDEX IF NOT EXISTS idx_trading_signals_side
    ON backtester.trading_signals(side);

CREATE INDEX IF NOT EXISTS idx_trading_signals_status
    ON backtester.trading_signals(status);

CREATE INDEX IF NOT EXISTS idx_trading_signals_strategy
    ON backtester.trading_signals(strategy_name);

CREATE INDEX IF NOT EXISTS idx_trading_signals_telegram_user
    ON backtester.trading_signals(telegram_user_id)
    WHERE telegram_user_id IS NOT NULL;

-- JSONB indexes for indicator queries
CREATE INDEX IF NOT EXISTS idx_trading_signals_indicators
    ON backtester.trading_signals USING GIN (indicators);

CREATE INDEX IF NOT EXISTS idx_trading_signals_strategy_config
    ON backtester.trading_signals USING GIN (strategy_config);

CREATE INDEX IF NOT EXISTS idx_trading_signals_dca_grid
    ON backtester.trading_signals USING GIN (dca_grid);

-- Composite index for recent signals by symbol
CREATE INDEX IF NOT EXISTS idx_trading_signals_symbol_timestamp
    ON backtester.trading_signals(symbol, timestamp DESC);

-- ============================================================================
-- Trigger for updated_at
-- ============================================================================

CREATE TRIGGER update_trading_signals_updated_at
    BEFORE UPDATE ON backtester.trading_signals
    FOR EACH ROW
    EXECUTE FUNCTION backtester.update_updated_at_column();

-- ============================================================================
-- Comments for documentation
-- ============================================================================

COMMENT ON TABLE backtester.trading_signals IS
    'Stores live trading signals generated by the signal generator';

COMMENT ON COLUMN backtester.trading_signals.signal_id IS
    'Unique identifier for the signal (UUID)';

COMMENT ON COLUMN backtester.trading_signals.indicators IS
    'JSON object containing indicator values at signal time (RSI, EMA, ADX, etc.)';

COMMENT ON COLUMN backtester.trading_signals.dca_grid IS
    'JSON array of DCA steps with price levels and multipliers';

COMMENT ON COLUMN backtester.trading_signals.quality_score IS
    'Signal quality score based on indicator confluence (0-100)';

COMMENT ON COLUMN backtester.trading_signals.status IS
    'Signal lifecycle status: pending -> notified -> executed/cancelled/expired';
