"""add_screener_extra_fields

Revision ID: 61685fee0c1a
Revises: c7c90767d1d9
Create Date: 2026-06-03 21:08:11.763674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61685fee0c1a'
down_revision: Union[str, None] = 'c7c90767d1d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('screener_snapshots', sa.Column('volume_1h', sa.Float(), nullable=False, server_default='0'))
    op.add_column('screener_snapshots', sa.Column('high_24h', sa.Float(), nullable=False, server_default='0'))
    op.add_column('screener_snapshots', sa.Column('low_24h', sa.Float(), nullable=False, server_default='0'))
    op.add_column('screener_snapshots', sa.Column('open_interest', sa.Float(), nullable=False, server_default='0'))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screener_snapshots', 'open_interest')
    op.drop_column('screener_snapshots', 'low_24h')
    op.drop_column('screener_snapshots', 'high_24h')
    op.drop_column('screener_snapshots', 'volume_1h')
    # ### end Alembic commands ###
