"""add_signal_log

Revision ID: afdec6d5c2dd
Revises: 61685fee0c1a
Create Date: 2026-06-03 21:42:00.599346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afdec6d5c2dd'
down_revision: Union[str, None] = '61685fee0c1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signal_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('entry_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('vol_1h_pct', sa.Float(), nullable=False),
    sa.Column('price_range_pct', sa.Float(), nullable=False),
    sa.Column('avg_candle_size_pct', sa.Float(), nullable=False),
    sa.Column('price_change_24h_pct', sa.Float(), nullable=False),
    sa.Column('funding_rate', sa.Float(), nullable=False),
    sa.Column('open_interest', sa.Float(), nullable=False),
    sa.Column('price_15m', sa.Float(), nullable=True),
    sa.Column('price_30m', sa.Float(), nullable=True),
    sa.Column('price_60m', sa.Float(), nullable=True),
    sa.Column('pnl_15m', sa.Float(), nullable=True),
    sa.Column('pnl_30m', sa.Float(), nullable=True),
    sa.Column('pnl_60m', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_log_entry_time'), 'signal_log', ['entry_time'], unique=False)
    op.create_index(op.f('ix_signal_log_id'), 'signal_log', ['id'], unique=False)
    op.create_index(op.f('ix_signal_log_symbol'), 'signal_log', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signal_log_symbol'), table_name='signal_log')
    op.drop_index(op.f('ix_signal_log_id'), table_name='signal_log')
    op.drop_index(op.f('ix_signal_log_entry_time'), table_name='signal_log')
    op.drop_table('signal_log')
    # ### end Alembic commands ###
