"""add_screener_snapshots

Revision ID: c7c90767d1d9
Revises: 1250a3c10be7
Create Date: 2026-06-03 20:50:32.561846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7c90767d1d9'
down_revision: Union[str, None] = '1250a3c10be7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screener_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('avg_candle_size_pct', sa.Float(), nullable=False),
    sa.Column('atr', sa.Float(), nullable=False),
    sa.Column('volume_24h', sa.Float(), nullable=False),
    sa.Column('volume_7d_avg', sa.Float(), nullable=False),
    sa.Column('volume_ratio', sa.Float(), nullable=False),
    sa.Column('funding_rate', sa.Float(), nullable=False),
    sa.Column('price_change_24h_pct', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('last_price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screener_snapshots_id'), 'screener_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_screener_snapshots_scanned_at'), 'screener_snapshots', ['scanned_at'], unique=False)
    op.create_index(op.f('ix_screener_snapshots_symbol'), 'screener_snapshots', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_screener_snapshots_symbol'), table_name='screener_snapshots')
    op.drop_index(op.f('ix_screener_snapshots_scanned_at'), table_name='screener_snapshots')
    op.drop_index(op.f('ix_screener_snapshots_id'), table_name='screener_snapshots')
    op.drop_table('screener_snapshots')
    # ### end Alembic commands ###
